# Generated by Django 5.2.7 on 2025-10-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='blank_profile_pic.png', upload_to='profile_images'),
        ),
    ]
