# Generated by Django 5.2.7 on 2025-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(blank=True, max_length=120)),
                ('user', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
